### ISSUE TITLE
Cannot access built-in declaration 'kotlin.IntArray'.

### ISSUE THREAD

**Issue by hadukin** [DRSchlaubi/contact_picker#40] opened 2021-07-03 17:38 UTC
Hi, when trying to build a project, I get an error:
Cannot access built-in declaration 'kotlin.IntArray'. Ensure that you have a dependency on the Kotlin standard library

**Comment by DRSchlaubi** [comment] 2021-07-03 17:52
Could you send your android/build.gradle and android/app/build.gradle?

maybe relates to #39, #38

**Comment by hadukin** [comment] 2021-07-03 18:21
it looks like the problem was with the kotlin version.
after i replaced the kotlin version in android/build.gradle 1.3.50 -> 1.5.20 i was able to build the application.

buildscript {
    ext.kotlin_version = '1.5.20'
    ...
}
...

**Comment by DRSchlaubi** [comment] 2021-07-03 20:11
Duplicate of #38

**Closed by DRSchlaubi** 2021-07-03 20:11 UTC
