### ISSUE TITLE
Can't build, ContactPicker.kt: (48, 280): Unresolved reference: stackTraceToString

### ISSUE THREAD

**Issue by jameskaguo777** [DRSchlaubi/contact_picker#32] opened 2021-04-27 11:27 UTC
I was integrating the plugin in my app and at first, DEBUG build failed with an error

```
\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluttercontactpicker-4.4.0\android\src\main\kotlin\me\schlaubi\fluttercontactpicker\ContactPicker.kt: (48, 280): Unresolved reference: stackTraceToString

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':fluttercontactpicker:compileDebugKotlin'.
> Compilation error. See log for more details

```
Can this be on my end or a general issue?

**Comment by DRSchlaubi** [comment] 2021-04-27 11:43
Duplicate of https://github.com/DRSchlaubi/contact_picker/issues/21#issuecomment-757674424

**Closed by DRSchlaubi** 2021-04-27 11:43 UTC
