### ISSUE TITLE
java.lang.NullPointerException when calling pickFullContact()

### ISSUE THREAD

**Issue by binoypatel** [DRSchlaubi/contact_picker#22] opened 2021-01-22 08:40 UTC
Hi there,

Thanks for this great plug-in. I am using this plug in with my flutter app. When I am calling pickFullContact then I am getting the following exception:

DE/AndroidRuntime(28970): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(28970): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime(28970): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime(28970): 	at android.app.Activity.dispatchActivityResult(Activity.java:8301)
E/AndroidRuntime(28970): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
E/AndroidRuntime(28970): 	... 11 more
I/Process (28970): Sending signal. PID: 28970 SIG: 9

And then the application hard crash. Not sure what I am doing wrong here. I am having Android 10 Nokia device.

Can you please help?

Thanks,
Binoy

**Comment by DRSchlaubi** [comment] 2021-01-22 08:47
This does not look like the full exception. Could you send me the full strack trace

**Comment by alkebuware** [comment] 2021-01-28 18:53
I came across this issue when searching if anyone had the same issue on Android. and figured I'd post my stacktrace, as I think I had the same crash as @binoypatel. The device I was testing on was a physical Android device Doogee N30 API 30. I was attempting to call FlutterContactPicker.pickFullContact(). I'm using version 4.2.1 of the plugin. Hope this helps.

D/AndroidRuntime(14150): Shutting down VM
E/AndroidRuntime(14150): FATAL EXCEPTION: main
E/AndroidRuntime(14150): Process: com.roadid.ecrumb.app, PID: 14150
E/AndroidRuntime(14150): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2029, result=-1, data=Intent { dat=content://com.android.contacts/contacts/lookup/2947i69c6552a8e1cc628/511 flg=0x1 }} to activity {com.roadid.ecrumb.app/com.example.ecrumbs_flutter.MainActivity}: java.lang.NullPointerException: it.getString(it.getColum…mmonDataKinds.Note.NOTE)) must not be null
E/AndroidRuntime(14150): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4873)
E/AndroidRuntime(14150): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4914)
E/AndroidRuntime(14150): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(14150): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14150): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14150): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
E/AndroidRuntime(14150): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14150): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(14150): 	at android.app.ActivityThread.main(ActivityThread.java:7389)
E/AndroidRuntime(14150): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14150): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(14150): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
E/AndroidRuntime(14150): Caused by: java.lang.NullPointerException: it.getString(it.getColum…mmonDataKinds.Note.NOTE)) must not be null
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker.getNote(ContactPicker.kt:112)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker.buildContact(ContactPicker.kt:99)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker.access$buildContact(ContactPicker.kt:18)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker$onActivityResult$3.invoke(ContactPicker.kt:47)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker$onActivityResult$3.invoke(ContactPicker.kt:18)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker.processContact(ContactPicker.kt:71)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.ContactPicker.onActivityResult(ContactPicker.kt:47)
E/AndroidRuntime(14150): 	at me.schlaubi.fluttercontactpicker.AbstractPickContext.onActivityResult(AbstractPickContext.kt:15)
E/AndroidRuntime(14150): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(14150): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(14150): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime(14150): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime(14150): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime(14150): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4866)
E/AndroidRuntime(14150): 	... 11 more

**Comment by DRSchlaubi** [comment] 2021-01-28 19:22
Does it happen with every contact?

**Comment by alkebuware** [comment] 2021-01-28 22:08
@DRSchlaubi Yes, everyone I've tried so far. I don't know if it helps a little, but these are contacts that were tied to my Google account from sometime ago. Around 5 years. I'm unsure if these contacts are missing that "it.getColum…mmonDataKinds.Note.NOTE" field because they were originally created on an older Android version. Hopefully that helps.

**Comment by DRSchlaubi** [comment] 2021-02-04 18:50
I pushed a fix to hotfix/npe, could you try if that works

**Comment by alkebuware** [comment] 2021-02-05 12:11
Ok I'll give it a try in a day or so. I'll let know how it goes as soon as I can.

**Comment by alkebuware** [comment] 2021-02-28 00:56
@DRSchlaubi Sorry it took so long for me to get back, but your fix on hotfix/npe works. Thanks!

**Closed** 2021-03-12 22:29 UTC
Labels: bug
