### ISSUE TITLE
App not building

### ISSUE THREAD

**Issue by g123k** [DRSchlaubi/contact_picker#41] opened 2021-07-03 21:22 UTC
Hello,

Since migrating to your lib in 4.5.x, my app can't be built anymore, due to this error:

```
Running Gradle task 'assembleDebug'...
e: /Users/g123k/.pub-cache/hosted/pub.dartlang.org/fluttercontactpicker-4.5.1/android/src/main/kotlin/me/schlaubi/fluttercontactpicker/ContactPicker.kt: (22, 115): Unresolved reference: lowercase

FAILURE: Build failed with an exception.
```

**Comment by DRSchlaubi** [comment] 2021-07-03 21:27
Duplicate of #39

**Closed by DRSchlaubi** 2021-07-03 21:27 UTC
