### ISSUE TITLE
Crashes on android

### ISSUE THREAD

**Issue by RalphMarvin** [DRSchlaubi/contact_picker#1] opened 2020-04-02 12:38 UTC
Anytime i pick a contact the app just crashes

**Comment by yosuanababan** [comment] 2020-04-07 02:45
me too

**Comment by RalphMarvin** [comment] 2020-04-07 09:18
> me too

I couldn't figure it out and I have a deadline in a few weeks, i ended up using *easy_contact_picker*, you'll have to customize it a bit, only thing is it doesn't have a search you'll have to implement that yourself. But i prefer that than a crash i know nothing about and cant figure out.

**Comment by DRSchlaubi** [comment] 2020-04-12 20:15
I completely missed that someone created an issue but could you provide some logs?

**Comment by DRSchlaubi** [comment] 2020-04-15 20:05
Okay I noticed an issue with app that still use v1 embedding and it should be fixed now.
@yosuanababan @RalphMarvin can you please try the new `2.2.0` version an tell me if it's fixed?

**Comment by RalphMarvin** [comment] 2020-04-15 20:41
Okay will do this week and will let you know.
Thanks

**Comment by Nyan274** [comment] 2020-04-17 06:03
Still crashing in 2.2.0
Here is the crash log

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2015, result=-1, data=Intent { dat=content://com.android.contacts/data/47 flg=0x1 }} to activity {packageName/packageName.MainActivity}: java.util.ConcurrentModificationException
E/AndroidRuntime(30092): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
E/AndroidRuntime(30092): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
E/AndroidRuntime(30092): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(30092): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(30092): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(30092): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
E/AndroidRuntime(30092): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(30092): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(30092): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(30092): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30092): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(30092): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime(30092): Caused by: java.util.ConcurrentModificationException
E/AndroidRuntime(30092): 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
E/AndroidRuntime(30092): 	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
E/AndroidRuntime(30092): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:633)
E/AndroidRuntime(30092): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(30092): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(30092): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(30092): 	at android.app.Activity.dispatchActivityResult(Activity.java:7797)
E/AndroidRuntime(30092): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
E/AndroidRuntime(30092): 	... 11 more

**Comment by DRSchlaubi** [comment] 2020-04-17 07:59
the app doesn't crash for me when picking a contact but it does when I do not  going to fix that in 2.2.1

**Comment by DRSchlaubi** [comment] 2020-04-17 08:13
Okay 2.2.1 is online now

**Comment by kinex** [comment] 2020-04-24 09:44
2.21 is still crashing, same exception. Maybe related to v2 embedding? So make sure your test app is using v2 embedding.

**Comment by kinex** [comment] 2020-04-24 09:54
Here is a sample of the Android embedding that works: https://github.com/kineapps/flutter_file_dialog/blob/master/android/src/main/kotlin/com/kineapps/flutter_file_dialog/FlutterFileDialogPlugin.kt

**Comment by DRSchlaubi** [comment] 2020-04-25 13:03
the example app uses v2 embedding and it works without any issues

**Comment by kinex** [comment] 2020-04-26 10:39
You could try selecting "Do not keep activities" in "Developer options". Maybe it helps reproducing the issue in your device? 

I think your calls to `activityBinding.removeActivityResultListener` may cause this issue. I would move that call to `onDetachedFromActivity` in any case.

**Comment by kinex** [comment] 2020-04-26 10:55
In your code `onDetachedFromActivityForConfigChanges` and `onDetachedFromEngine` don't do anything? That is also not correct. I really recommend you verify all your embedding related code. See the link in my earlier message or compare your code to some official Flutter plugin (which is `ActivityAware`).

**Comment by DRSchlaubi** [comment] 2020-04-26 12:59
I am still unable to reproduce this but I changed some embedding things so if you could try using the version from the master branch and tell me if anything changes

**Comment by kinex** [comment] 2020-04-26 14:45
I made a quick test and it seems to work now (btw my test device is Galaxy S7 / Android 8). I noticed one issue: you updated channel name but forgot to update it in the Dart code. A made a local fix to be able to test it.

**Comment by DRSchlaubi** [comment] 2020-04-26 15:40
I though I updated it but maybe I did not VCS it

**Comment by DRSchlaubi** [comment] 2020-04-27 12:21
there is version 2.3.0 now could please everyone here try it

**Comment by JonathanVegasP** [comment] 2020-04-27 20:49
I had the same problem with other plugin and this, but, after upgrading to 2.3.0 it worked fine on Flutter 1.12.13-hotfix9. Thanks for bringing us the solution!

**Comment by DRSchlaubi** [comment] 2020-04-27 21:28
Going to close this issue since the issue seems to be gone now

**Closed by DRSchlaubi** 2020-04-27 21:28 UTC

**Comment by aqualaguna** [comment] 2020-11-02 08:09
Still got this error 
Lib version: 3.1.0
